---
- name: Install keepalived
  apt:
    name: keepalived
    state: latest

- name: Copy keepalived config file
  copy:
    src: roles/keepalivedmaster/templates/keepalived_master.conf
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: "0644"

- name: restart keepalived service
  systemd:
    name: keepalived.service
    state: restarted
